### ISSUE TITLE
Token standards

### ISSUE THREAD

**Issue by 0xBreadguy** [vechain/nft-registry#1]
I think it'd be useful to have optional flags for token standards used for specific contracts. 

ERC-721
ERC-1155
Royalties
Subscriptions
Burnable
Special methods that allows you to block competing marketplaces
etc

This would allow quick lists to be able to be made for ecosystem tokens that are suitable for given dapps

**Comment by ifavo** [comment]
@Bread-VeSea great idea!

I think we should keep it simple at first, detecting the flags for supporting a specific standards is a good extension, the other ones are more complicated :)

**Comment by ifavo** [comment]
A snapshot of the chain data is now made during build, it contains currently:

1. ERC-721 flag
2. ERC-1155 flag
3. `name` of the contract

Example:

```json
    "chainData": {
      "name": "VeChain Node Token",
      "supportedInterfaces": {
        "erc721": false,
        "erc1155": false
      }
    }
```

**Comment by 0xBreadguy** [comment]
Nice. Would it be helpful to gather the methods for standard royalty, burnable and the subscriptions I had mentioned? I would say those are pretty crucial for how the collection can or should be extended

**Comment by ifavo** [comment]
This was the easiest one to add, so it was the first step.

Can you point me to some standard ABI to use for detecting these add-ons?

**Comment by ifavo** [comment]
The following interfaces are now detected, ERC 20, 165, 712, 721, 777, 1155, 2981, 1820, 721+Metadata, 721+Enumerable, 721+Receiver

Burnable + Subscriptions missing, happy for suggestions :-)

**Comment by 0xBreadguy** [comment]
Here's a compilation of ERC standards and extensions that seem appropriate:

Burnable: 
ERC20Burnable
ERC721Burnable

Subscriptions:
IERC5643 - There isn't a "standard" yet, but this EIP is the one with the most traction tied tightly to ERC721 and one we're looking to adopt. (https://ethereum-magicians.org/t/eip-5643-subscription-nfts/10802/44)

Royalties:
ERC2981


I looked through the other mature proposals (those in "Last Call" and "Review" status) and didn't see anything that would be immediately useful.

**Comment by 0xBreadguy** [comment]
Hmmm, digging deeper in to this I see that there may not be standardized interfaces for a few of these. That or I'm perhaps not great at tracking down the signatures for the interfaces.

**Comment by ifavo** [comment]
Do you know a way to detect burnable? The others we covered by now.

**Comment by 0xBreadguy** [comment]
I've been scouring for any indication of interfaces for it and haven't found any, no. It's a standard extension and widely used, however:

[OpenZepplin - ERC20Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Burnable.sol)
[OpenZepplin - ERC721Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Burnable.sol)

**Comment by ifavo** [comment]
> I've been scouring for any indication of interfaces for it and haven't found any, no. It's a standard extension and widely used, however:
> 
> 
> 
> [OpenZepplin - ERC20Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Burnable.sol)
> 
> [OpenZepplin - ERC721Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Burnable.sol)
> 
> 

I am using the same source but since I don't see a specific definition of supportsInterfaces I see no simple way right now. I will close this issue and when we find a way, we can extend it.
